# Generated by Django 2.2.4 on 2019-09-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myattendance', '0004_studententries_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studententries',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
